### ISSUE TITLE
goodbye dpi çalıştırdığımda 3 tane error veriyo

### ISSUE THREAD

**Issue by sikikma** [cagritaskn/GoodbyeDPI-Turkey#10]
![Ekran Görüntüsü (513)](https://github.com/user-attachments/assets/02128edf-98b1-4bc0-93b5-82862c3d9ca9)
turkey_dnsredir.cmd çalıştırıyorum bu hata geliyo diğerlerini çalıştırıncada bu hata geliyo internetim türk telekom

**Comment by cagritaskn** [comment]
3 sebepten dolayı bu sorunu yaşıyor olabilirsiniz.
-Antivirüs programınız WinDivert dosyalarını engelliyor.
-Batch dosyasını yönetici olarak çalıştırmadınız.
-Zip dosyasını ayıkladığınızda ayıklanmış dosyaların bazılarının konumları değişti.

Zip dosyasını ayıkladığınız klasörün tamamını antivirüs programınızın İstisnalar/Dışlamalar kısmına ekleyerek, dosyayı yönetici olarak çalıştırarak ve .zip dosyasını ayıkladıktan sonra dosyaların yerini değiştirmeyerek bu sorunu çözmeyi deneyebilirsiniz.

**Comment by sikikma** [comment]
knk dc eklesene yapamadım .semihpro

**Comment by cagritaskn** [comment]
Maalesef bireysel yardımda bulunamıyorum. Program yaklaşık 200 bin indirmeye ulaştı herkese teker teker yardımcı olmam imkansız. Rehberi tekrar gözden geçirip anti-virüs programınızı kapatın, yönetici olarak çalıştırmayı unutmayın, dosyaların yerlerini değiştirmeyin.
