### ISSUE TITLE
Xbox Gamepass oyunları hata veriyor

### ISSUE THREAD

**Issue by ZeploiT** [cagritaskn/GoodbyeDPI-Turkey#11]
İşletim sistemi

Win 11

Bu hizmet bilgisayarda açıkken gamepass oyunları açılmıyor, hata verip kapanıyor. Bu servisi kapatıp bilgisayarı restart ettikten sonra oyunlar açılıyor. Buna bir çözüm bulabilir misin?

**Comment by cagritaskn** [comment]
Başlatmaya çalıştığınız oyunun ismi nedir ?
Hata kodu alıyorsanız bu kodu benimle paylaşır mısınız ?

**Comment by ZeploiT** [comment]
Gamepass üzerinden bir kaç oyunu denedim ama sadece Call of Duty oyununda hata alıyor. 

0x0 hatası alıyor şu şekilde 
![image](https://github.com/user-attachments/assets/16a9f145-0cd6-4b40-809a-6d63e3f2d78b)

**Comment by cagritaskn** [comment]
Bu sorunu aşağıdaki adreste bulunan tartışma konusunun altında cevapladım :
**[Bazı Oyunların Açılmama Problemine Çözüm Var Mı ?](https://github.com/cagritaskn/GoodbyeDPI-Turkey/discussions/2#discussioncomment-11294808)**
