### ISSUE TITLE
Kod açık kaynak kodlu DEĞİL

### ISSUE THREAD

**Issue by t0int1337** [cagritaskn/GoodbyeDPI-Turkey#12]
### I've made sure there's no existing feature request / Böyle bir özelliğin daha önce önerilmediğinden emin oldum

- [X] I've made sure there's no existing feature request / Böyle bir özelliğin daha önce önerilmediğinden emin oldum

### Describe your feature / Önerinizi açıklayın

Source dizininde size ait hiçbir commit yok. Lütfen kaynak kodlarını yayınlayın.

**Comment by cagritaskn** [comment]
- GoodbyeDPI.exe:
Goodbyedpi.exe için kaynak kodları reponun /src klasöründe bulunuyor. [Buradan](https://github.com/cagritaskn/GoodbyeDPI-Turkey/tree/master/src) goodbyedpi.exe'nin kaynak kodlarına erişebilirsiniz. C Programlama diline hakim iseniz bu proje üzerinde düzenleme de yapabilirsiniz. [TCC : Tiny C Compiler](http://bellard.org/tcc/) ya da benzeri kolay ve ücretsiz bulabileceğiniz bir programla da bu kaynak dosyalarını derleyip kendiniz sıfırdan .exe oluşturabilirsiniz.

- CMD Dosyaları:
.CMD dosyaları şifrelenmemiş (un-encrypted) olduğundan herhangi bir metin düzenleyici ile açıp içerisinde ne olduğuna bakabilirsiniz. 

- WinDivert SYS ve DLL Dosyaları:
Buradan WinDivert kütüphanesinin açık kaynak kodlarına ulaşabilirsiniz: [WinDivert 2.2: Windows Packet Divert](https://github.com/basil00/WinDivert)
WinDivert kütüphanesi doğrudan resmi repositorysinden alıp kullanıldı. Dilerseniz projedekileri silip tekrar aynı konuma aynı binaryleri indirip kullanabilirsiniz.

- Özet:
Projenin [README.md](https://github.com/cagritaskn/GoodbyeDPI-Turkey/blob/master/README.md) dosyasını dikkatli şekilde okursanız benim yaptığımın bir fork olduğunu, orijinal proje olmadığını, yalnızca komut dosyalarını Türkiye için doğru şekilde uyarlayıp herkesin anlayabileceği şekilde bir anlatım hazırladığımı göreceksiniz. Benim fork'uma ait commitleri görmek için [Release](https://github.com/cagritaskn/GoodbyeDPI-Turkey/releases/tag/release-0.2.3rc3-turkey) sayfasındaki değişiklik günlüğüne bakabilirsiniz. Kısacası kaynak kodlarının tamamı erişilebilir. Program tamamen ücretsiz ve açık kaynak kodlu. Ayrıca programı kullanıp kullanmamak kullanıcının inisiyatifinde. Lütfen insanları galeyana getirecek şekilde söylemlerden kaçının.

**Comment by nukleermuffin** [comment]
Elinizesağlık

**Comment by Cabbar1t** [comment]
be goddbayı ındırıdım indrmede felan sorun yasamadım ama turkey_dnsredir actıgımda hata veriyor hatada su (godbyedpi.exe tarafından bulunamıyor.isi doğru yazıldıgındna emin olup yeniden deneyin diye hata veriyor napmam lazım vidosu var eya benım gii hata aln varmı
