### ISSUE TITLE
GoodbyeDPİ Açılmıyor

### ISSUE THREAD

**Issue by Crecooo** [cagritaskn/GoodbyeDPI-Turkey#13]
GoodbyeDPİ ı açtığımda 
![resim_2024-12-04_150600812](https://github.com/user-attachments/assets/d0e3ece7-f8ef-4623-9918-d4d963300086)
ek te bıraktığım hatayı alıyorum

**Comment by cagritaskn** [comment]
- ZIP dosyasını ayıkladığınız klasörde bırakıp hiçbir dosyanın yerini değiştirmeyin
- Antivirüs programınız var ve aktif ise devre dışı bırakın
- Çalıştır > services.msc (ya da Başlat > Hizmetler) işlemlerini takip ederek listede GoodbyeDPI ve WinDivert isimli hizmetlerin yüklü olup olmadığını kontrol edin
- service_remove.cmd dosyasını yönetici olarak çalıştırıp talimatları takip edin ardından aynısını service_dnsredir_turkey.cmd dosyası için gerçekleştirip bilgisayarınızı yeniden başlatın
