### ISSUE TITLE
Programı ethernet ile kullandığımda çalışmıyor ama wifi ile çalışıyor 

### ISSUE THREAD

**Issue by Lozhert** [cagritaskn/GoodbyeDPI-Turkey#14]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Soruları veya “çalışmayan web sitesi” raporlarını buradan bildirerek, sorunlar bölümünü kötüye kullanırsam depodan engellenebileceğimi anlıyorum.

### Operating system / İşletim sistemi

Windows 11 x64

### Running as service / Servis olarak çalıştırma

I run it as a regular program / Programı normal bir şekilde çalıştırıyorum

### Describe the bug / Hata açıklaması

turkey_dnsredir_alternative_superonline.cmd dosyasını wifi ile çalıştırdığımda sorun çıkmıyor ama aynı dosyayı ethernet ile kullanmaya çalışırsam hiçbir siteye veya discorda erişemiyorum

**Comment by FlySquare** [comment]
selam, şuan aynı dosyayı test ettim 2 farklı network ile bir sorun göremedim sağlıklı çalıştı, farklı bir sebebi olabilir belki.

**Comment by cagritaskn** [comment]
Bahsettiğiniz sorun nadir rastlanan bir sorun. Bir önceki yanıtta arkadaşımızın bahsettiği gibi bu kurumla çalıştıranlar olduğundan sizin sisteminize ait bir değişkenin soruna yol açması muhtemel görünüyor.

Bu sorun yüzlerce hatta binlerce farklı değişkene bağlı olduğundan birçok sebebi olabilir. İndirdiğiniz uygulamalar, kullandığınız tünel veya proxyler, cihazınız ya da modeminizdeki herhangi bir DNS ayarı, bağlantıyı sağladığınız sağlayıcı vs. tonlarca sebebi olabilir. Maalesef bireysel destek verip her kişinin sorununu derinlemesine inceleme şansımız yok. 

Önerebileceğim tek çözüm adaptörlerden kullanmadığınızı (Örneğin LAN kullanacaksanız Wi-Fi adaptörünü) devre dışı bırakıp bilgisayarınızı yeniden başlattıktan sonra denemeniz.
