### ISSUE TITLE
Program Çalışmıyor

### ISSUE THREAD

**Issue by Hwaanx** [cagritaskn/GoodbyeDPI-Turkey#18]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Soruları veya “çalışmayan web sitesi” raporlarını buradan bildirerek, sorunlar bölümünü kötüye kullanırsam depodan engellenebileceğimi anlıyorum.

### Operating system / İşletim sistemi

Windows 11 23H2

### Running as service / Servis olarak çalıştırma

I run it as a regular program / Programı normal bir şekilde çalıştırıyorum

### Describe the bug / Hata açıklaması

GoodbyeDpi bir anda çalışmamaya başladı ve devamında bir internet kesikliği oluştu, bende Turkey versiyonu çıkmış onu indireyim dedim. Service İnstall denedim olmadı. Service İnstall + restart denedim olmadı. Normal bir şekilde açtım olmadı. DNS'i 1.1.1.1 olarak değiştirdim olmadı ne yapsam olmuyor. Millenicom Kullanıyorum. En sonunda normal goodbyedpi'i tekrar indirdim ve sorun çözüldü.

**Comment by cagritaskn** [comment]
Yaşadığınız sorunun birçok nedeni olabilir ancak en sık karşılaşılan sorunlara yönelik çözüm önerileri:
- Antivirüs programınız var ise (özellikle Kaspersky) bunu kapatarak deneyin.
- ZIP klasörünü ayıkladığınız konumdaki klasör ve dosyaların yerini asla değiştirmeyin.
- Hizmetlere girip GoodByeDPI isimli hizmetin çalışıp çalışmadığını kontrol edin ve eğer çalışmıyorsa sağ tıklayıp Başlat seçeneğini seçin.
- Komut dosyalarının tamamını yönetici olarak çalıştırdığınızdan emin olun.

Unutmayın ki GoodByeDPI hiçbir sağlayıcı, cihaz veya yasaklı uygulama/site için çalışma garantisi vermez.

**Comment by Hwaanx** [comment]
Antirüs kapalı
Dosyalara ellemedim
Yönetici olarak çalıştırdım tabikide.

17 Ara 2024 Sal 22:59 tarihinde Çağrı Taşkın ***@***.***>
şunu yazdı:

**Comment by Hwaanx** [comment]
bozuk program maalesef çalışmıyor
