### ISSUE TITLE
Call Of Duty Warzone Açılmıyor

### ISSUE THREAD

**Issue by wantrox** [cagritaskn/GoodbyeDPI-Turkey#4]
### CAPTCHA

- [X] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Я понимаю, что меня могут заблокировать в репозитории, если я буду использовать раздел issue не для сообщений об ошибках, а для вопросов или сообщении о «неработающем веб-сайте».

### Operating system / операционная система

Windows 11 23h2

### Running as service / Запуск программы как сервис

I installed it as a service / Установил как сервис Windows

### Describe the bug / Опишите ошибку программы

Servisi yüklediğimden beri call of duty warzone açamıyorum easy anticheat ekranı geliyor yüklenmeden kapanıyor steam ve battle.net ikisinide denedim diğer forumlara baktım goodbyedpi yüzünden olduğunu söyleyenler var arkadaşımda da goodbyedpi var ve oda açamıyor yardımcı olurmusunuz

**Comment by cagritaskn** [comment]
Bu sorunu aşağıdaki adreste bulunan tartışma konusunun altında cevapladım :
**[Bazı Oyunların Açılmama Problemine Çözüm Var Mı?](https://github.com/cagritaskn/GoodbyeDPI-Turkey/discussions/2#discussioncomment-11294808)**
