### ISSUE TITLE
açmayı denerken sebebini anlamadığım bir hata veriyor

### ISSUE THREAD

**Issue by Elecksy** [cagritaskn/GoodbyeDPI-Turkey#5]
![image](https://github.com/user-attachments/assets/5baa9db7-fb27-4ffa-b3bf-ea53761ba857)
böyle bir şey ile karşılaşıyorum

**Comment by cagritaskn** [comment]
Discord'a herhangi başka bir şekilde erişiminiz var ise bana ulaşabilir misiniz ? Ben bu hatayı almadığımdan bu sorunu yaşayan birisinin bilgisayarında deneyerek çözmem gerekebilir. Discord kullanıcı ismim: kegrisko. (Sonunda nokta var.)

**Comment by MQuer** [comment]
Merhaba bende buna benzer bir sorun yaşıyorum discorddan size arkadaşlık isteği attım yüklediniz dosyada ki cmd dosyaları açıldığı gibi kapanıyor ya da sürekli yenisini açıp hata vermeye devam ediyor discord kapandığından beri kullanıyordum ama bugün açılmadı yüklemeye çalıştığımda da sürekli hata aldım internette bir çok yere baktım ama çözüm yolunu bulamadım
![WhatsApp Görsel 2024-11-21 saat 01 06 04_06f680b9](https://github.com/user-attachments/assets/fcae425c-d540-4875-8b66-38e527b1ac78)

**Comment by cagritaskn** [comment]
@Elecksy sayesinde hata çözüldü. **[Bu sayfadan](https://github.com/cagritaskn/GoodbyeDPI-Turkey/releases/download/release-0.2.3rc3-turkey/goodbyedpi-0.2.3rc3-turkey.zip)** tekrar indirme gerçekleştirip kurulum yapabilirsiniz.
