### ISSUE TITLE
MacOS Versiyonu

### ISSUE THREAD

**Issue by yavuzsebe** [cagritaskn/GoodbyeDPI-Turkey#6]
MacOS versiyonu yazabilir misiniz?

**Comment by cagritaskn** [comment]
Hocam ben maalesef yazamam ancak [Zapret](https://github.com/bol-van/zapret) isimli programın MacOS'ta çalıştığını söylüyorlar. Dilerseniz bir araştırma yapıp kullanımını öğrenebilirsiniz.
