### ISSUE TITLE
Türksatta çalışmıyor

### ISSUE THREAD

**Issue by Bekra99** [cagritaskn/GoodbyeDPI-Turkey#7]
Elinize sağlık hocam ancak belirtmek isterim ki Türksatta çalışmıyor. Orjinal proje de çalışmıyordu

**Comment by cagritaskn** [comment]
Hocam alternatif metodları denediniz mi ? Türksat'ta da çalıştığını söyleyen başka Türksat kullanıcıları var.

**Comment by Tanerx** [comment]
> Elinize sağlık hocam ancak belirtmek isterim ki Türksatta çalışmıyor. Orjinal proje de çalışmıyordu

Normal (alternatif olmayan) olan sorunsuz çalışıyor.

**Comment by ibrahimsenx** [comment]
> Hocam alternatif metodları denediniz mi ? Türksat'ta da çalıştığını söyleyen başka Türksat kullanıcıları var.

Discord'da sadece turkey_dnsredir'i arkada açık bırakınca çalışıyor. Diğer sitelerde buna gerek kalmıyor.

**Comment by cagritaskn** [comment]
> > Hocam alternatif metodları denediniz mi ? Türksat'ta da çalıştığını söyleyen başka Türksat kullanıcıları var.
> 
> Discord'da sadece turkey_dnsredir'i arkada açık bırakınca çalışıyor. Diğer sitelerde buna gerek kalmıyor. 

Bunu yapmak yerine aynı protokolü kullanan ancak hizmet kurulumuyla çalışan service_install_dnsredir_turkey.cmd  komut dosyasını yönetici olarak çalıştırıp bilgisayarınızı yeniden başlatırsanız durmadan kapatıp açmanıza gerek kalmaz.
