### ISSUE TITLE
Hiperonline'da çalışmıyor

### ISSUE THREAD

**Issue by Xonevia** [cagritaskn/GoodbyeDPI-Turkey#8]
### CAPTCHA

- [x] I understand I could be banned from the repository if I misusing issue section not for posting bugs, but for question or 'broken website' report. / Soruları veya “çalışmayan web sitesi” raporlarını buradan bildirerek, sorunlar bölümünü kötüye kullanırsam depodan engellenebileceğimi anlıyorum.

### Operating system / İşletim sistemi

Win10

### Running as service / Servis olarak çalıştırma

I run it as a regular program / Programı normal bir şekilde çalıştırıyorum

### Describe the bug / Hata açıklaması

technopat sayfasındaki işlemlerin çoğunu denedim ama yinede çalışmadı

**Comment by cagritaskn** [comment]
Maalesef bu program tüm servis sağlayıcılarında, tüm web sitelerinin açılacağına dair bir garanti vermiyor. Alternatif çözüm yollarında anlatılanları da uygulayarak sonuca ulaşamadıysanız daha fazla yardımcı olamayız.
Aşağıda linklerini koyacağım benzer projelere göz atarak sizin için işe yarayanı bulabilirsiniz:

- [zapret](https://github.com/bol-van/zapret) by @bol-van (for MacOS, Linux and Windows)
- [Green Tunnel](https://github.com/SadeghHayeri/GreenTunnel) by @SadeghHayeri (for MacOS, Linux and Windows)
- [SpoofDPI-Platform](https://github.com/r3pr3ss10n/SpoofDPI-Platform) by @r3pr3ss10n (for Android, macOS, Windows)
- [ByeDPI](https://github.com/hufrea/byedpi) for Linux/Windows
- [PowerTunnel](https://github.com/krlvm/PowerTunnel) by @krlvm (for Windows, MacOS and Linux)

**Comment by taroxzen** [comment]
Süperonline için araya DNS sunucusu eklemek şart, aşağıda belirtiğim yolu izle gibi olursa GoodbyeDPI-Turkey programını kullanırsın.
Ayarlar>Ağ ve internet>Ethernet>DNS suncusu ataması>Düzenle ve resimdeki verileri gir.
![DNS](https://github.com/user-attachments/assets/0646a365-deb0-4cb8-803e-1d8458ecd655)
